security:
    providers:
        users_in_memory: { memory: null }
    firewalls:
        dev:
            pattern: ^/api/doc|(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            lazy: true
