carts:
  type: rest
  prefix: /api
  resource: App\Controller\CartsController

products:
  type: rest
  prefix: /api
  resource: App\Controller\ProductsController

app.swagger_ui:
  path: /api/doc
  methods: GET
  defaults: { _controller: nelmio_api_doc.controller.swagger_ui }
